
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khalo
 */
public class FENETRE_QUIZ extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FENETRE_QUIZ.class.getName());

    /**
     * Creates new form FENETRE_QUIZ
     */
    public FENETRE_QUIZ() {
        
        ArrayList<String> Tab = new ArrayList<String>();
        Tab.add("1) Quel mot-clé permet de définir une classe en Java ?\n a) class  b) define  c) struct  d) module");
        Tab.add("2) Quel type permet de stocker un entier ?\n a) float  b) boolean  c) int  d) char");
        Tab.add("3) Comment afficher du texte ?\n a) echo()  b) System.print()  c) Console.write()  d) System.out.println()");
        Tab.add("4) Quel opérateur compare l’égalité ?\n a) =  b) ==  c) ===  d) =>");
        Tab.add("5) Quel type de retour indique qu'une méthode ne renvoie rien ?\n a) null  b) void  c) empty  d) none");
        
        initComponents();
        afficherQuestionCourante();
    }
    private void afficherQuestionCourante(){
     Questions q = ListeQuestions.get(indexQuestionCourante);
q.melangerReponses();   
        
    intitule.setText(Question.getIntitule());
    proposition1.setText(Question.getProposition1());
    proposition2.setText(Question.getProposition2());
    proposition3.setText(Question.getProposition3());
    proposition4.setText(Question.getProposition4());
    enonce.setText(texte);
    .setEnabled(true);
        B.setEnabled(true);
        C.setEnabled(true);
        D.setEnabled(true);
    }
    
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question = new javax.swing.JLabel();
        Proposition1 = new javax.swing.JButton();
        Proposition2 = new javax.swing.JButton();
        Proposition3 = new javax.swing.JButton();
        Proposition4 = new javax.swing.JButton();
        FEEDBACK = new javax.swing.JLabel();
        Question_suivante = new javax.swing.JButton();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question.setText("Question");

        Proposition1.setText("Proposition1");
        Proposition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proposition1ActionPerformed(evt);
            }
        });

        Proposition2.setText("Proposition2");

        Proposition3.setText("Proposition3");
        Proposition3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proposition3ActionPerformed(evt);
            }
        });

        Proposition4.setText("Proposition4");

        FEEDBACK.setText("FEEDBACK");

        Question_suivante.setText("Question suivante");

        score.setText("score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Proposition3)
                        .addGap(46, 46, 46)
                        .addComponent(Proposition2)
                        .addGap(57, 57, 57)
                        .addComponent(Proposition1)
                        .addGap(57, 57, 57)
                        .addComponent(Proposition4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Question))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(FEEDBACK)))
                        .addGap(502, 502, 502)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question_suivante)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question)
                    .addComponent(score))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proposition3)
                    .addComponent(Proposition2)
                    .addComponent(Proposition1)
                    .addComponent(Proposition4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FEEDBACK)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Question_suivante)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Proposition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proposition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Proposition1ActionPerformed

    private void Proposition3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proposition3ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_Proposition3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FENETRE_QUIZ().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FEEDBACK;
    private javax.swing.JButton Proposition1;
    private javax.swing.JButton Proposition2;
    private javax.swing.JButton Proposition3;
    private javax.swing.JButton Proposition4;
    private javax.swing.JLabel Question;
    private javax.swing.JButton Question_suivante;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables

    private void afficherQuestionCourante() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
