/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khalo
 */
public class principal_class extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal_class.class.getName());
    Combinaison combiTestee;
    Combinaison combiSecrete;
    

    /**
     * Creates new form principal_class
     */
    public principal_class() {
    
        int a,b,c,d;
        initComponents();
      
         Combinaison jeu = new Combinaison();
        a=(int) (Math.random()*10);
        b=(int) (Math.random()*10);
        c=(int) (Math.random()*10);
        d=(int) (Math.random()*10); 
         initComponents();
        jeu = new Combinaison(); // création de l’objet
        jeu.genererCombiAleat();
   
        
        
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        texte_intro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 64, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 64, -1, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 64, -1, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 64, -1, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 130, 94, -1));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 198, -1, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 198, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 198, -1, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 198, -1, -1));

                        texte_chiffre_0.setText("0");
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 133, 37, -1));

                        texte_chiffre_1.setText("0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 133, 37, -1));

                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 133, 37, -1));

                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 133, 37, -1));

                        texte_lbl_nb_chiffres_exacts.setText("Nbr de chiffres exactes :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 255, 146, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 37, -1));

                        texte_lbl_nb_chiffres_haut.setText("Nbr de chiffres trops hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 277, -1, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 37, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nbr de chiffres trops bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 299, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 43, -1));

                        texte_score.setText("0");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 219, 43, -1));

                        texte_tentatives.setText("tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 191, 68, -1));

                        texte_intro.setText("Trouvez le bon code en moins de 5 tentatives :");
                        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 18, 268, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
 jeu.augmenter                             // ajouter 1
texte_chiffre_1.setText("+jeu.getCombiTestee()[3]);        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
int valeurActuelle = Integer.parseInt(texte_chiffre_2.getText());  // récupérer la valeur actuelle
if (valeurActuelle < 9) {        // si on n'a pas encore atteint 9
    valeurActuelle++;            // on ajoute 1
    };                                              // ajouter 1
texte_chiffre_2.setText(String.valueOf(valeurActuelle));          // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
       int valeurActuelle = Integer.parseInt(texte_chiffre_3.getText());  // récupérer la valeur actuelle
if (valeurActuelle < 9) {        // si on n'a pas encore atteint 9
    valeurActuelle++;            // on ajoute 1
    };                                              // ajouter 1
texte_chiffre_3.setText(String.valueOf(valeurActuelle));//  // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
         int valeurActuelle = Integer.parseInt(texte_chiffre_0.getText());  // récupérer la valeur actuelle
if (valeurActuelle < 9) {        // si on n'a pas encore atteint 9
    valeurActuelle++;            // on ajoute 1
    };                                              // ajouter 1
texte_chiffre_0.setText(String.valueOf(valeurActuelle));// TODO add your handling code here:
jeu.augmenterChiffre(0);
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
int valeurActuelle = Integer.parseInt(texte_chiffre_0.getText());
        if (valeurActuelle > 0) {    // si on n'est pas déjà à 0
    valeurActuelle--;        // on retire 1
}

texte_chiffre_0.setText(Integer.toString(valeurActuelle));        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
int valeurActuelle = Integer.parseInt(texte_chiffre_1.getText());
        if (valeurActuelle > 0) {    // si on n'est pas déjà à 0
    valeurActuelle--;        // on retire 1
}

texte_chiffre_1.setText(Integer.toString(valeurActuelle));          // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
int valeurActuelle = Integer.parseInt(texte_chiffre_2.getText());
        if (valeurActuelle > 0) {    // si on n'est pas déjà à 0
    valeurActuelle--;        // on retire 1
}

texte_chiffre_2.setText(Integer.toString(valeurActuelle));          // TODO add your handling code here:
             // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
 int valeurActuelle = Integer.parseInt(texte_chiffre_3.getText());
        if (valeurActuelle > 0) {    // si on n'est pas déjà à 0
    valeurActuelle--;        // on retire 1
}

texte_chiffre_3.setText(Integer.toString(valeurActuelle));     
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
texte_chiffre_0.setText("0");
texte_chiffre_1.setText("0");
texte_chiffre_2.setText("0");
texte_chiffre_3.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed

    
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()->new principal_class().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables

}